#!/bin/sh
set -x
sudo docker rm -f dg-controller-kubeclient
sleep 2
sudo mvn clean install -Pdocker-build-image -DskipTests
sleep 2
sudo docker images | sed -n '2p'
#sudo docker run -it --name dg-controller-kubeclient dg-controller-kubeclient:latest

#sudo mvn clean install -Pdocker-push-image
#mvn -Ddocker.username=jkong85 -Ddocker.password=19851208 docker:push

